import type { Metadata } from "next";
import { ReactNode } from "react";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<>
			<Head>
				<meta charSet="utf-8" />
				<title>{metadata.title as string}</title>
				<meta name="description" content={metadata.description || ""} />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<body>{children}</body>
		</>
	);
}
